worker_processes 1;
error_log /dev/null emerg;

events {
    worker_connections 512;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    access_log off;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout 30;

    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_comp_level 6;
    gzip_types
        text/plain
        text/css
        text/xml
        text/javascript
        application/javascript
        application/json
        application/xml
        image/svg+xml;

    gzip_disable "msie6";

    server {
        listen 80;
        root /usr/share/nginx/html;

        error_page 404 = /404_empty;
        
        location = /404_empty {
            return 204;
        }


        # 访问域名根路径 / 时,指向 /usr/share/nginx/html/user 目录
        location / {
            # 覆盖根目录为用户端目录
            root /usr/share/nginx/html/user;
            index index.html index.htm;

            # 静态资源缓存 (原配置中的缓存逻辑移到这里)
            expires 1d;
            add_header Cache-Control "public, immutable";
        }

        # 访问 /author/ 路径时,指向 /usr/share/nginx/html/author 目录
        location /author/ {
            index index.html index.htm;
            # 静态资源缓存
            expires 1d;
            add_header Cache-Control "public, immutable";
        }
    }
    
}