"""alter book and book chapter

Revision ID: 23a74856cce7
Revises: f68809adc1b9
Create Date: 2026-04-30 11:51:22.903188

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "23a74856cce7"
down_revision: str | None = "f68809adc1b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("book_ibfk_1"), "book", type_="foreignkey")
    op.drop_constraint(op.f("book_ibfk_2"), "book", type_="foreignkey")
    op.drop_index(op.f("ix_book_child_id"), table_name="book")
    op.drop_index(op.f("ix_book_parent_id"), table_name="book")
    op.drop_constraint(op.f("book_chapter_ibfk_1"), "book_chapter", type_="foreignkey")
    op.drop_constraint(op.f("book_chapter_ibfk_2"), "book_chapter", type_="foreignkey")
    op.drop_index(op.f("ix_book_chapter_child_id"), table_name="book_chapter")
    op.drop_index(op.f("ix_book_chapter_parent_id"), table_name="book_chapter")
    op.create_foreign_key(None, "book_chapter", "book_chapter", ["parent_id"], ["id"])
    op.create_foreign_key(None, "book_chapter", "book_chapter", ["child_id"], ["id"])
    op.drop_column("book_chapter", "is_updating")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book_chapter",
        sa.Column(
            "is_updating",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "book_chapter", type_="foreignkey")
    op.drop_constraint(None, "book_chapter", type_="foreignkey")
    # 先创建外键约再创建索引会自动创建索引
    op.create_foreign_key(
        op.f("book_chapter_ibfk_2"), "book_chapter", "book", ["parent_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("book_chapter_ibfk_3"),
        "book_chapter",
        "book_chapter",
        ["child_id"],
        ["id"],
    )
    # book 表的外键约束会自动创建索引无需手动创建
    op.create_foreign_key(op.f("book_ibfk_1"), "book", "book", ["parent_id"], ["id"])
    op.create_foreign_key(op.f("book_ibfk_2"), "book", "book", ["child_id"], ["id"])
    # ### end Alembic commands ###
