"""initial

Revision ID: 344050318daa
Revises:
Create Date: 2026-01-23 00:23:38.809621

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "344050318daa"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cover", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tags", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("total_chapter", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("words_cnt", sa.Integer(), nullable=False),
        sa.Column("is_ended", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_category_is_ended", "book", ["category", "is_ended"], unique=False
    )
    op.create_index(
        "idx_category_words", "book", ["category", "words_cnt"], unique=False
    )
    op.create_index(op.f("ix_book_author"), "book", ["author"], unique=False)
    op.create_index(op.f("ix_book_category"), "book", ["category"], unique=False)
    op.create_index(op.f("ix_book_is_ended"), "book", ["is_ended"], unique=False)
    op.create_index(op.f("ix_book_name"), "book", ["name"], unique=False)
    op.create_index(
        op.f("ix_book_total_chapter"), "book", ["total_chapter"], unique=False
    )
    op.create_index(op.f("ix_book_words_cnt"), "book", ["words_cnt"], unique=False)
    op.create_table(
        "permission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "resource_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "action", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False
        ),
        sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
        sa.Column("bit_position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bit_position"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        "index_unique_code",
        "permission",
        ["resource_type", "action", "scope"],
        unique=True,
    )
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("avatar", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    op.create_index(op.f("ix_user_password"), "user", ["password"], unique=False)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=False)
    op.create_table(
        "author",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_author_name"), "author", ["name"], unique=True)
    op.create_index(op.f("ix_author_user_id"), "author", ["user_id"], unique=True)
    op.create_table(
        "book_chapter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sort_order", sa.Float(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "index_book_sort_unique", "book_chapter", ["book_id", "sort_order"], unique=True
    )
    op.create_index(
        op.f("ix_book_chapter_book_id"), "book_chapter", ["book_id"], unique=False
    )
    op.create_index(
        op.f("ix_book_chapter_sort_order"), "book_chapter", ["sort_order"], unique=False
    )
    op.create_table(
        "book_chapter_draft",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sort_order", sa.Float(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "action",
            sa.Enum(
                "READ",
                "CREATE",
                "UPDATE",
                "DELETE",
                "AUDIT",
                "MANAGE",
                name="actionenum",
            ),
            nullable=True,
        ),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "REVIEWING",
                "APPROVED",
                "REJECTED",
                name="bookdraftstatusenum",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "index_book_chapter_draft_unique",
        "book_chapter_draft",
        ["book_id", "sort_order"],
        unique=True,
    )
    op.create_index(
        op.f("ix_book_chapter_draft_book_id"),
        "book_chapter_draft",
        ["book_id"],
        unique=False,
    )
    op.create_table(
        "role_inheritance",
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.CheckConstraint(
            "child_id != parent_id", name="child_id_not_equal_parent_id"
        ),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("child_id", "parent_id"),
    )
    op.create_table(
        "role_permission",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permission.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "shelf",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "index_user_book_unique", "shelf", ["user_id", "book_id"], unique=True
    )
    op.create_index(op.f("ix_shelf_book_id"), "shelf", ["book_id"], unique=False)
    op.create_index(op.f("ix_shelf_user_id"), "shelf", ["user_id"], unique=False)
    op.create_table(
        "user_role",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("granted_by", sa.Integer(), nullable=True),
        sa.Column(
            "granted_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "author_book",
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["author.id"],
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.PrimaryKeyConstraint("author_id", "book_id"),
    )
    op.create_index(
        op.f("ix_author_book_author_id"), "author_book", ["author_id"], unique=False
    )
    op.create_index(
        op.f("ix_author_book_book_id"), "author_book", ["book_id"], unique=False
    )
    op.create_table(
        "book_draft",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cover", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tags", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "READ",
                "CREATE",
                "UPDATE",
                "DELETE",
                "AUDIT",
                "MANAGE",
                name="actionenum",
            ),
            nullable=True,
        ),
        sa.Column("book_id", sa.Integer(), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "REVIEWING",
                "APPROVED",
                "REJECTED",
                name="bookdraftstatusenum",
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["author.id"],
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_book_draft_unique",
        "book_draft",
        ["name", "author_id", "action"],
        unique=True,
    )
    op.create_index(
        op.f("ix_book_draft_author"), "book_draft", ["author"], unique=False
    )
    op.create_index(
        op.f("ix_book_draft_author_id"), "book_draft", ["author_id"], unique=False
    )
    op.create_index(
        op.f("ix_book_draft_book_id"), "book_draft", ["book_id"], unique=False
    )
    op.create_index(
        op.f("ix_book_draft_category"), "book_draft", ["category"], unique=False
    )
    op.create_index(op.f("ix_book_draft_name"), "book_draft", ["name"], unique=False)
    op.create_table(
        "user_reading_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("last_chapter_id", sa.Integer(), nullable=False),
        sa.Column("last_position", sa.Integer(), nullable=False),
        sa.Column("last_read_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_chapter_id"],
            ["book_chapter.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "index_user_book_unique",
        "user_reading_progress",
        ["user_id", "book_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_user_reading_progress_book_id"),
        "user_reading_progress",
        ["book_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_reading_progress_last_chapter_id"),
        "user_reading_progress",
        ["last_chapter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_reading_progress_user_id"),
        "user_reading_progress",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_reading_progress_user_id"), table_name="user_reading_progress"
    )
    op.drop_index(
        op.f("ix_user_reading_progress_last_chapter_id"),
        table_name="user_reading_progress",
    )
    op.drop_index(
        op.f("ix_user_reading_progress_book_id"), table_name="user_reading_progress"
    )
    op.drop_index("index_user_book_unique", table_name="user_reading_progress")
    op.drop_table("user_reading_progress")
    op.drop_index(op.f("ix_book_draft_name"), table_name="book_draft")
    op.drop_index(op.f("ix_book_draft_category"), table_name="book_draft")
    op.drop_index(op.f("ix_book_draft_book_id"), table_name="book_draft")
    op.drop_index(op.f("ix_book_draft_author_id"), table_name="book_draft")
    op.drop_index(op.f("ix_book_draft_author"), table_name="book_draft")
    op.drop_index("idx_book_draft_unique", table_name="book_draft")
    op.drop_table("book_draft")
    op.drop_index(op.f("ix_author_book_book_id"), table_name="author_book")
    op.drop_index(op.f("ix_author_book_author_id"), table_name="author_book")
    op.drop_table("author_book")
    op.drop_table("user_role")
    op.drop_index(op.f("ix_shelf_user_id"), table_name="shelf")
    op.drop_index(op.f("ix_shelf_book_id"), table_name="shelf")
    op.drop_index("index_user_book_unique", table_name="shelf")
    op.drop_table("shelf")
    op.drop_table("role_permission")
    op.drop_table("role_inheritance")
    op.drop_index(
        op.f("ix_book_chapter_draft_book_id"), table_name="book_chapter_draft"
    )
    op.drop_index("index_book_chapter_draft_unique", table_name="book_chapter_draft")
    op.drop_table("book_chapter_draft")
    op.drop_index(op.f("ix_book_chapter_sort_order"), table_name="book_chapter")
    op.drop_index(op.f("ix_book_chapter_book_id"), table_name="book_chapter")
    op.drop_index("index_book_sort_unique", table_name="book_chapter")
    op.drop_table("book_chapter")
    op.drop_index(op.f("ix_author_user_id"), table_name="author")
    op.drop_index(op.f("ix_author_name"), table_name="author")
    op.drop_table("author")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_password"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_table("role")
    op.drop_index("index_unique_code", table_name="permission")
    op.drop_table("permission")
    op.drop_index(op.f("ix_book_words_cnt"), table_name="book")
    op.drop_index(op.f("ix_book_total_chapter"), table_name="book")
    op.drop_index(op.f("ix_book_name"), table_name="book")
    op.drop_index(op.f("ix_book_is_ended"), table_name="book")
    op.drop_index(op.f("ix_book_category"), table_name="book")
    op.drop_index(op.f("ix_book_author"), table_name="book")
    op.drop_index("idx_category_words", table_name="book")
    op.drop_index("idx_category_is_ended", table_name="book")
    op.drop_table("book")
    # ### end Alembic commands ###
