"""remove the id field of the author table

Revision ID: 37821b9518f1
Revises: b51f47b16784
Create Date: 2026-04-28 16:50:59.446716

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "37821b9518f1"
down_revision: str | None = "b51f47b16784"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查并删除外键约束
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    # 检查并删除 book_draft 表的外键约束
    fk_constraints = inspector.get_foreign_keys("book_draft")
    for fk in fk_constraints:
        if fk.get("name") == "book_draft_ibfk_1":
            op.drop_constraint(
                op.f("book_draft_ibfk_1"), "book_draft", type_="foreignkey"
            )
            break
    # 检查 author_book 表的外键约束
    fk_constraints = inspector.get_foreign_keys("author_book")
    for fk in fk_constraints:
        if fk.get("name") == "author_book_ibfk_1":
            op.drop_constraint(
                op.f("author_book_ibfk_1"), "author_book", type_="foreignkey"
            )
            break

    # 检查并添加 author_book 表的 user_id 列如果不存在
    columns = inspector.get_columns("author_book")
    if not any(col["name"] == "user_id" for col in columns):
        op.add_column("author_book", sa.Column("user_id", sa.Integer(), nullable=False))

    # 检查并删除索引
    indexes = inspector.get_indexes("author_book")
    for idx in indexes:
        if idx.get("name") == "ix_author_book_author_id":
            op.drop_index(op.f("ix_author_book_author_id"), table_name="author_book")
            break

    # 检查并删除 author 表的 id 列
    columns = inspector.get_columns("author")
    if any(col["name"] == "id" for col in columns):
        op.drop_column("author", "id")

    # 检查并删除 author_book 表的 author_id 列
    columns = inspector.get_columns("author_book")
    if any(col["name"] == "author_id" for col in columns):
        op.drop_column("author_book", "author_id")

    # 检查并创建 author_book 表的索引和外键如果不存在
    indexes = inspector.get_indexes("author_book")
    if not any(idx.get("name") == "ix_author_book_user_id" for idx in indexes):
        op.create_index(
            op.f("ix_author_book_user_id"), "author_book", ["user_id"], unique=False
        )

    fk_constraints = inspector.get_foreign_keys("author_book")
    if not any(
        fk.get("name") and "user_id" in str(fk.get("constrained_columns", []))
        for fk in fk_constraints
    ):
        op.create_foreign_key(None, "author_book", "user", ["user_id"], ["id"])

    # 检查并添加 book_draft 表的 user_id 列如果不存在
    columns = inspector.get_columns("book_draft")
    if not any(col["name"] == "user_id" for col in columns):
        op.add_column("book_draft", sa.Column("user_id", sa.Integer(), nullable=False))

    # 检查并删除 book_draft 表的索引
    indexes = inspector.get_indexes("book_draft")
    for idx in indexes:
        if idx.get("name") == "ix_book_draft_author_id":
            op.drop_index(op.f("ix_book_draft_author_id"), table_name="book_draft")
            break

    for idx in indexes:
        if idx.get("name") == "idx_book_draft_unique":
            op.drop_index(op.f("idx_book_draft_unique"), table_name="book_draft")
            break

    # 检查并创建 book_draft 表的索引和外键如果不存在
    indexes = inspector.get_indexes("book_draft")
    if not any(idx.get("name") == "idx_book_draft_unique" for idx in indexes):
        op.create_index(
            "idx_book_draft_unique",
            "book_draft",
            ["name", "user_id", "action"],
            unique=True,
        )

    if not any(idx.get("name") == "ix_book_draft_user_id" for idx in indexes):
        op.create_index(
            op.f("ix_book_draft_user_id"), "book_draft", ["user_id"], unique=False
        )

    # 检查并创建 book_draft 表的外键约束如果不存在
    fk_constraints = inspector.get_foreign_keys("book_draft")
    if not any(
        fk.get("name") and "user_id" in str(fk.get("constrained_columns", []))
        for fk in fk_constraints
    ):
        op.create_foreign_key(None, "book_draft", "user", ["user_id"], ["id"])

    # 检查并删除 book_draft 表的 author_id 列
    columns = inspector.get_columns("book_draft")
    if any(col["name"] == "author_id" for col in columns):
        op.drop_column("book_draft", "author_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book_draft",
        sa.Column("author_id", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "book_draft", type_="foreignkey")
    op.create_foreign_key(
        op.f("book_draft_ibfk_1"), "book_draft", "author", ["author_id"], ["id"]
    )
    op.drop_index(op.f("ix_book_draft_user_id"), table_name="book_draft")
    op.drop_index("idx_book_draft_unique", table_name="book_draft")
    op.create_index(
        op.f("idx_book_draft_unique"),
        "book_draft",
        ["name", "author_id", "action"],
        unique=True,
    )
    op.create_index(
        op.f("ix_book_draft_author_id"), "book_draft", ["author_id"], unique=False
    )
    op.alter_column(
        "book_draft", "book_id", existing_type=mysql.INTEGER(), nullable=True
    )
    op.drop_column("book_draft", "user_id")
    op.add_column(
        "author_book",
        sa.Column("author_id", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "author_book", type_="foreignkey")
    op.create_foreign_key(
        op.f("author_book_ibfk_1"), "author_book", "author", ["author_id"], ["id"]
    )
    op.drop_index(op.f("ix_author_book_user_id"), table_name="author_book")
    op.create_index(
        op.f("ix_author_book_author_id"), "author_book", ["author_id"], unique=False
    )
    op.drop_column("author_book", "user_id")
    op.add_column(
        "author", sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False)
    )
    # ### end Alembic commands ###
