"""delete_sort_order

Revision ID: 3fe1b7a49112
Revises: 58396c9dfdba
Create Date: 2026-04-30 15:22:18.979957

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "3fe1b7a49112"
down_revision: str | None = "58396c9dfdba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book_chapter", "sort_order")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book_chapter", sa.Column("sort_order", mysql.FLOAT(), nullable=False)
    )
    # ### end Alembic commands ###
