"""alter

Revision ID: 58396c9dfdba
Revises: d87250dc2e85
Create Date: 2026-04-30 15:19:38.677234

"""

from collections.abc import Sequence

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "58396c9dfdba"
down_revision: str | None = "d87250dc2e85"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "book_chapter", "sort_order", existing_type=mysql.FLOAT(), nullable=False
    )
    op.drop_index(op.f("index_book_sort_unique"), table_name="book_chapter")
    op.drop_index(op.f("ix_book_chapter_sort_order"), table_name="book_chapter")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_book_chapter_sort_order"), "book_chapter", ["sort_order"], unique=False
    )
    op.create_index(
        op.f("index_book_sort_unique"),
        "book_chapter",
        ["book_id", "sort_order"],
        unique=True,
    )
    op.alter_column(
        "book_chapter", "sort_order", existing_type=mysql.FLOAT(), nullable=True
    )
    # ### end Alembic commands ###
