"""parent_id_del

Revision ID: 880ec572d006
Revises: d76b1f91637b
Create Date: 2026-05-01 23:43:04.557234

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "880ec572d006"
down_revision: str | None = "d76b1f91637b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("book_chapter_ibfk_1"), "book_chapter", type_="foreignkey")
    op.drop_column("book_chapter", "parent_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book_chapter",
        sa.Column("parent_id", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("book_chapter_ibfk_1"),
        "book_chapter",
        "book_chapter",
        ["parent_id"],
        ["id"],
    )
    # ### end Alembic commands ###
