"""alter_statistic

Revision ID: b51f47b16784
Revises: dc9331907708
Create Date: 2026-03-19 20:20:43.454121

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "b51f47b16784"
down_revision: str | None = "dc9331907708"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chapter_read_statistics",
        sa.Column("total_duration", sa.Float(), nullable=False),
    )
    op.drop_column("chapter_read_statistics", "avg_read_duration_sec")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chapter_read_statistics",
        sa.Column(
            "avg_read_duration_sec",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("chapter_read_statistics", "total_duration")
    # ### end Alembic commands ###
