"""alter

Revision ID: d54b0e211f52
Revises: 23a74856cce7
Create Date: 2026-04-30 12:20:43.227574

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d54b0e211f52"
down_revision: str | None = "23a74856cce7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "book", "book", ["parent_id"], ["id"])
    op.drop_column("book", "child_id")
    op.drop_constraint(op.f("book_chapter_ibfk_2"), "book_chapter", type_="foreignkey")
    op.create_foreign_key(None, "book_chapter", "book", ["book_id"], ["id"])
    op.drop_column("book_chapter", "child_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book_chapter",
        sa.Column("child_id", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "book_chapter", type_="foreignkey")
    op.create_foreign_key(
        op.f("book_chapter_ibfk_2"),
        "book_chapter",
        "book_chapter",
        ["child_id"],
        ["id"],
    )
    op.add_column(
        "book",
        sa.Column("child_id", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "book", type_="foreignkey")
    # ### end Alembic commands ###
