"""order

Revision ID: d76b1f91637b
Revises: 3fe1b7a49112
Create Date: 2026-05-01 23:20:11.752902

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d76b1f91637b"
down_revision: str | None = "3fe1b7a49112"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("book_chapter", sa.Column("order", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book_chapter", "order")
    # ### end Alembic commands ###
