"""alter_sort_order

Revision ID: d87250dc2e85
Revises: d54b0e211f52
Create Date: 2026-04-30 14:50:32.038370

"""

from collections.abc import Sequence

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d87250dc2e85"
down_revision: str | None = "d54b0e211f52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "book_chapter", "sort_order", existing_type=mysql.FLOAT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "book_chapter", "sort_order", existing_type=mysql.FLOAT(), nullable=False
    )
    # ### end Alembic commands ###
