"""add_statistics

Revision ID: dc9331907708
Revises: 344050318daa
Create Date: 2026-02-05 16:30:29.503762

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc9331907708"
down_revision: str | None = "344050318daa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chapter_read_statistics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("chapter_id", sa.Integer(), nullable=False),
        sa.Column(
            "hour_start",
            sa.DateTime(),
            nullable=False,
            comment="Hour-aligned timestamp (e.g., '2026-02-05 14:00:00')",
        ),
        sa.Column("unique_reader_count", sa.Integer(), nullable=False),
        sa.Column("page_view_count", sa.Integer(), nullable=False),
        sa.Column("avg_read_duration_sec", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["book_chapter.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_book_hour",
        "chapter_read_statistics",
        ["book_id", "hour_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chapter_read_statistics_book_id"),
        "chapter_read_statistics",
        ["book_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chapter_read_statistics_chapter_id"),
        "chapter_read_statistics",
        ["chapter_id"],
        unique=False,
    )
    op.create_index(
        "ix_hour_start", "chapter_read_statistics", ["hour_start"], unique=False
    )
    op.create_index(
        "uq_chapter_hour",
        "chapter_read_statistics",
        ["book_id", "chapter_id", "hour_start"],
        unique=True,
    )
    op.create_table(
        "user_read_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("chapter_id", sa.Integer(), nullable=False),
        sa.Column(
            "event_time", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "event_type",
            sa.Enum("ENTER", "EXIT", "HEATBEAT", name="reportenum"),
            nullable=False,
            comment="Event type",
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["book_chapter.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_book_chapter_time",
        "user_read_event",
        ["book_id", "chapter_id", "event_time"],
        unique=False,
    )
    op.create_index("ix_event_time", "user_read_event", ["event_time"], unique=False)
    op.create_index(
        "ix_user_book_chapter",
        "user_read_event",
        ["user_id", "book_id", "chapter_id", "event_time"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_book_chapter", table_name="user_read_event")
    op.drop_index("ix_event_time", table_name="user_read_event")
    op.drop_index("ix_book_chapter_time", table_name="user_read_event")
    op.drop_table("user_read_event")
    op.drop_index("uq_chapter_hour", table_name="chapter_read_statistics")
    op.drop_index("ix_hour_start", table_name="chapter_read_statistics")
    op.drop_index(
        op.f("ix_chapter_read_statistics_chapter_id"),
        table_name="chapter_read_statistics",
    )
    op.drop_index(
        op.f("ix_chapter_read_statistics_book_id"), table_name="chapter_read_statistics"
    )
    op.drop_index("ix_book_hour", table_name="chapter_read_statistics")
    op.drop_table("chapter_read_statistics")
    # ### end Alembic commands ###
