"""initial

Revision ID: f68809adc1b9
Revises:
Create Date: 2026-04-30 00:59:17.397006

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f68809adc1b9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("book", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("book", sa.Column("is_updating", sa.Boolean(), nullable=False))
    op.add_column(
        "book_chapter",
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "REVIEWING",
                "APPROVED",
                "REJECTED",
                "PUBLISHED",
                name="bookstatusenum",
            ),
            server_default="pending",
            nullable=True,
        ),
    )
    op.add_column("book_chapter", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column(
        "book_chapter", sa.Column("is_updating", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book_chapter", "is_updating")
    op.drop_column("book_chapter", "is_active")
    op.drop_column("book_chapter", "status")
    op.drop_column("book", "is_updating")
    op.drop_column("book", "is_active")
    # ### end Alembic commands ###
