ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.qianrenni.HttpKt.configureHttp
      - com.qianrenni.SecurityKt.configureSecurity
      - com.qianrenni.RateLimitingKt.configureRateLimiting
      - com.qianrenni.StatusPagesKt.configureStatusPages
      - com.qianrenni.ResourcesKt.configureResources
      - com.qianrenni.AutoHeadResponseKt.configureAutoHeadResponse
      - com.qianrenni.RoutingKt.configureRouting
